# Generated by Django 3.2.6 on 2021-08-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='award',
            field=models.ManyToManyField(null=True, to='movie.Award'),
        ),
    ]
