# Generated by Django 3.2.6 on 2021-08-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210825_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='award',
            field=models.ManyToManyField(to='movie.Award'),
        ),
    ]
